import { useAuthStore } from '../store/useAuthStore'

const PERMISSIONS: Record<number, Record<string, boolean>> = {
  0: {
    viewDashboard: true, viewKhata: true,
    manageKhata: true, viewContacts: true,
    manageContacts: true, viewInvoices: true,
    createInvoices: true, deleteInvoices: true,
    viewInventory: true, manageInventory: true,
    viewPurchase: true, managePurchase: true,
    usePOS: true, viewReports: true,
    viewFinancialReports: true, viewHR: true,
    manageHR: true, viewPayroll: true,
    managePayroll: true, viewExpenses: true,
    manageExpenses: true, viewSettings: true,
    manageSettings: true, manageTeam: true,
    viewDamagedGoods: true,
    manageDamagedGoods: true,
  },
  1: {
    viewDashboard: true, viewKhata: true,
    manageKhata: true, viewContacts: true,
    manageContacts: true, viewInvoices: true,
    createInvoices: true, deleteInvoices: false,
    viewInventory: true, manageInventory: true,
    viewPurchase: true, managePurchase: true,
    usePOS: true, viewReports: true,
    viewFinancialReports: true, viewHR: true,
    manageHR: false, viewPayroll: true,
    managePayroll: false, viewExpenses: true,
    manageExpenses: true, viewSettings: true,
    manageSettings: false, manageTeam: false,
    viewDamagedGoods: true,
    manageDamagedGoods: true,
  },
  2: {
    viewDashboard: true, viewKhata: true,
    manageKhata: true, viewContacts: true,
    manageContacts: false, viewInvoices: true,
    createInvoices: true, deleteInvoices: false,
    viewInventory: true, manageInventory: false,
    viewPurchase: true, managePurchase: false,
    usePOS: false, viewReports: true,
    viewFinancialReports: true, viewHR: false,
    manageHR: false, viewPayroll: true,
    managePayroll: false, viewExpenses: true,
    manageExpenses: true, viewSettings: false,
    manageSettings: false, manageTeam: false,
    viewDamagedGoods: true,
    manageDamagedGoods: false,
  },
  3: {
    viewDashboard: true, viewKhata: true,
    manageKhata: true, viewContacts: true,
    manageContacts: true, viewInvoices: true,
    createInvoices: true, deleteInvoices: false,
    viewInventory: true, manageInventory: false,
    viewPurchase: false, managePurchase: false,
    usePOS: true, viewReports: false,
    viewFinancialReports: false, viewHR: false,
    manageHR: false, viewPayroll: false,
    managePayroll: false, viewExpenses: false,
    manageExpenses: false, viewSettings: false,
    manageSettings: false, manageTeam: false,
    viewDamagedGoods: false,
    manageDamagedGoods: false,
  },
  4: {
    viewDashboard: false, viewKhata: false,
    manageKhata: false, viewContacts: false,
    manageContacts: false, viewInvoices: false,
    createInvoices: false, deleteInvoices: false,
    viewInventory: true, manageInventory: false,
    viewPurchase: false, managePurchase: false,
    usePOS: true, viewReports: false,
    viewFinancialReports: false, viewHR: false,
    manageHR: false, viewPayroll: false,
    managePayroll: false, viewExpenses: false,
    manageExpenses: false, viewSettings: false,
    manageSettings: false, manageTeam: false,
    viewDamagedGoods: false,
    manageDamagedGoods: false,
  },
  5: {
    viewDashboard: true, viewKhata: true,
    manageKhata: true, viewContacts: true,
    manageContacts: true, viewInvoices: true,
    createInvoices: true, deleteInvoices: true,
    viewInventory: true, manageInventory: true,
    viewPurchase: true, managePurchase: true,
    usePOS: true, viewReports: true,
    viewFinancialReports: true, viewHR: true,
    manageHR: true, viewPayroll: true,
    managePayroll: true, viewExpenses: true,
    manageExpenses: true, viewSettings: true,
    manageSettings: true, manageTeam: true,
    viewDamagedGoods: true,
    manageDamagedGoods: true,
  },
  6: {
    viewDashboard: true, viewKhata: false,
    manageKhata: false, viewContacts: true,
    manageContacts: false, viewInvoices: false,
    createInvoices: false, deleteInvoices: false,
    viewInventory: false, manageInventory: false,
    viewPurchase: false, managePurchase: false,
    usePOS: false, viewReports: false,
    viewFinancialReports: false, viewHR: true,
    manageHR: true, viewPayroll: true,
    managePayroll: true, viewExpenses: false,
    manageExpenses: false, viewSettings: false,
    manageSettings: false, manageTeam: false,
    viewDamagedGoods: false,
    manageDamagedGoods: false,
  },
}

export function usePermissions() {
  const { user } = useAuthStore()
  const role = user?.role ?? -1
  const perms = PERMISSIONS[role] ?? {}

  return {
    can: (permission: string): boolean => perms[permission] ?? false,
    role,
    isOwnerOrAdmin: role === 0 || role === 1 || role === 5,
    isSuperAdmin: role === 0,
    isOwner: role === 5,
    isAccountant: role === 2,
    isSales: role === 3,
    isPOSOperator: role === 4,
    isHRManager: role === 6,
  }
}
