namespace BizCore.Application.DTOs.Subscription;

public record SubscriptionPlanDto(
    Guid Id,
    string Name,
    string Code,
    string? Description,
    decimal MonthlyPrice,
    decimal AnnualPrice,
    decimal SetupFee,
    int MaxUsers,
    int MaxProducts,
    int MaxInvoices,
    int MaxWarehouses,
    int MaxBranches,
    int MaxStorageMB,
    bool AllowPOS,
    bool AllowInventory,
    bool AllowInvoices,
    bool AllowExpenses,
    bool AllowPurchase,
    bool AllowStockTransfer,
    bool AllowPayroll,
    bool AllowProjects,
    bool AllowReports,
    bool AllowMultipleBranches,
    bool AllowMultiWarehouse,
    bool AllowAPI,
    bool AllowCustomBranding,
    bool IsActive,
    bool IsDefault,
    int SortOrder,
    int TrialDays);

public record CreateSubscriptionPlanDto(
    string Name,
    string Code,
    string? Description,
    decimal MonthlyPrice,
    decimal AnnualPrice,
    decimal SetupFee,
    int MaxUsers,
    int MaxProducts,
    int MaxInvoices,
    int MaxWarehouses,
    int MaxBranches,
    int MaxStorageMB,
    bool AllowPOS,
    bool AllowInventory,
    bool AllowInvoices,
    bool AllowExpenses,
    bool AllowPurchase,
    bool AllowStockTransfer,
    bool AllowPayroll,
    bool AllowProjects,
    bool AllowReports,
    bool AllowMultipleBranches,
    bool AllowMultiWarehouse,
    bool AllowAPI,
    bool AllowCustomBranding,
    bool IsActive,
    bool IsDefault,
    int SortOrder,
    int TrialDays);

public record BusinessSubscriptionDto(
    Guid Id,
    Guid BusinessId,
    string BusinessName,
    Guid PlanId,
    string PlanName,
    DateTime StartDate,
    DateTime? ExpiryDate,
    string Status,
    string BillingCycle,
    decimal PaidAmount,
    bool IsTrial,
    DateTime? TrialEndDate);

public record AssignPlanDto(
    Guid BusinessId,
    Guid PlanId,
    string BillingCycle,
    int TrialDays);

public record FeatureAccessDto(
    bool HasPOS,
    bool HasInventory,
    bool HasInvoices,
    bool HasExpenses,
    bool HasPurchase,
    bool HasStockTransfer,
    bool HasPayroll,
    bool HasProjects,
    bool HasReports,
    bool HasMultipleBranches,
    bool HasMultiWarehouse,
    bool HasAPI,
    bool HasCustomBranding,
    int MaxUsers,
    int MaxProducts,
    int MaxInvoices,
    int MaxWarehouses,
    int MaxBranches,
    string PlanName = "Free",
    string PlanCode = "FREE");